AWSTemplateFormatVersion: '2010-09-09'
Description: Frontend deployment for Data Room application

Parameters:
  Stage:
    Type: String
    Description: The deployment stage (dev, staging, prod)
  
  ApiEndpoint:
    Type: String
    Description: The API Gateway endpoint URL
  
  DomainName:
    Type: String
    Description: Optional custom domain name
    Default: ""

Conditions:
  HasCustomDomain: !Not [!Equals [!Ref DomainName, ""]]

Resources:
  # S3 bucket for static website hosting
  FrontendBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "data-room-frontend-${Stage}"
      AccessControl: Private
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
  
  # Bucket policy to allow CloudFront access
  FrontendBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref FrontendBucket
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              CanonicalUser: !GetAtt CloudFrontOAI.S3CanonicalUserId
            Action: s3:GetObject
            Resource: !Sub "${FrontendBucket.Arn}/*"
  
  # CloudFront origin access identity
  CloudFrontOAI:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: !Sub "OAI for Data Room Frontend - ${Stage}"

  # CloudFront distribution
  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Aliases: !If [HasCustomDomain, [!Ref DomainName], !Ref "AWS::NoValue"]
        Origins:
          - Id: S3Origin
            DomainName: !GetAtt FrontendBucket.RegionalDomainName
            S3OriginConfig:
              OriginAccessIdentity: !Sub "origin-access-identity/cloudfront/${CloudFrontOAI}"
        Enabled: true
        HttpVersion: http2
        DefaultRootObject: index.html
        CustomErrorResponses:
          - ErrorCode: 403
            ResponseCode: 200
            ResponsePagePath: /index.html
          - ErrorCode: 404
            ResponseCode: 200
            ResponsePagePath: /index.html
        DefaultCacheBehavior:
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
          CachedMethods:
            - GET
            - HEAD
            - OPTIONS
          TargetOriginId: S3Origin
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
          ViewerProtocolPolicy: redirect-to-https
          Compress: true
          DefaultTTL: 3600
        PriceClass: PriceClass_100
        ViewerCertificate:
          CloudFrontDefaultCertificate: !If [HasCustomDomain, false, true]
          AcmCertificateArn: !If [HasCustomDomain, !Sub "arn:aws:acm:us-east-1:${AWS::AccountId}:certificate/your-acm-certificate-id", !Ref "AWS::NoValue"]
          SslSupportMethod: !If [HasCustomDomain, "sni-only", !Ref "AWS::NoValue"]
          MinimumProtocolVersion: !If [HasCustomDomain, "TLSv1.2_2021", !Ref "AWS::NoValue"]

Outputs:
  FrontendBucketName:
    Description: "S3 Bucket for frontend hosting"
    Value: !Ref FrontendBucket
    Export:
      Name: !Sub "${AWS::StackName}-FrontendBucketName"

  FrontendBucketArn:
    Description: "ARN of the Frontend S3 Bucket"
    Value: !GetAtt FrontendBucket.Arn
    Export:
      Name: !Sub "${AWS::StackName}-FrontendBucketArn"

  CloudFrontDistributionId:
    Description: "ID of CloudFront distribution"
    Value: !Ref CloudFrontDistribution
    Export:
      Name: !Sub "${AWS::StackName}-CloudFrontDistributionId"

  CloudFrontDomainName:
    Description: "Domain name of CloudFront distribution"
    Value: !GetAtt CloudFrontDistribution.DomainName
    Export:
      Name: !Sub "${AWS::StackName}-CloudFrontDomainName"